image: Visual Studio 2017

init:
  - git config --global core.autocrlf input
environment:
  WINFLEXBISON_VERSION: 2.5.15
install:
  - python -m pip install Mako==1.0.7
  # Install pywin32 extensions, needed by SCons
  - python -m pip install pypiwin32
  - python -m pip install --upgrade pip setuptools wheel
  - python -m pip install scons==3.0.1
  - scons --version
  - set WINFLEXBISON_ARCHIVE=win_flex_bison-%WINFLEXBISON_VERSION%.zip
  - if not exist "%WINFLEXBISON_ARCHIVE%" appveyor DownloadFile "https://datapacket.dl.sourceforge.net/project/winflexbison/old_versions/%WINFLEXBISON_ARCHIVE%"
  - 7z x -y -owinflexbison\ "%WINFLEXBISON_ARCHIVE%" > nul
  - set Path=%CD%\winflexbison;%Path%
  - win_flex --version
build_script:
  - build.bat
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))