name: Mesa Binary Build

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - master
      - develop
      - feature/ghaction
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    env:
        WINFLEXBISON_VERSION: 2.5.15
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: 
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: |
          Set-PSDebug -Trace 1
          python -m pip install Mako
          $WINFLEXBISON_VERSION=$Env.WINFLEXBISON_VERSION
          $WINFLEXBISON_ARCHIVE="win_flex_bison-$WINFLEXBISON_VERSION.zip"
          "https://github.com/lexxmark/winflexbison/releases/download/v$WINFLEXBISON_VERSION/$WINFLEXBISON_ARCHIVE"
          Invoke-WebRequest -Uri "https://github.com/lexxmark/winflexbison/releases/download/v$WINFLEXBISON_VERSION/$WINFLEXBISON_ARCHIVE" -OutFile $WINFLEXBISON_ARCHIVE
          
          7z x -y -owinflexbison\ "$WINFLEXBISON_ARCHIVE"
          win_flex --version
          New-Item -ItemType Directory -Force -Path build
          New-Item -ItemType Directory -Force -Path build\x86
          New-Item -ItemType Directory -Force -Path build\x86_64
      shell: pwsh
    - name: Clone mesa
      run: git clone https://gitlab.freedesktop.org/mesa/mesa.git
    - name: Build 32-Bit
      run: cmd "/K" '"$VCInstallDir\Auxiliary\Build\vcvars32.bat" && powershell ./build32.ps1'
      shell: pwsh
    - name: Build 64-Bit
      run: cmd "/K" '"$VCInstallDir\Auxiliary\Build\vcvars64.bat" && powershell ./build64.ps1'
      shell: pwsh
    - name: 'Upload Full OpenGL'
      uses: actions/upload-artifact@v2
      with:
        name: opengl_win
        path: build/**
    - name: 'Upload OpenGL Library only'
      uses: actions/upload-artifact@v2
      with:
        name: opengl_win
        path: build/**/*.dll
