name: LLVM Build

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - main
      - feature/ghaction
  pull_request:
    branches:
      - main
jobs:
  build:
        
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        arch: [ x86 ]
        os: [windows-latest]
        include:
          - arch: x64
            os: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: |
            git clone https://github.com/Microsoft/vcpkg.git
            ./vcpkg/bootstrap-vcpkg.bat
      shell: pwsh
    - name: Patch VCPKG for Release
      run: |
        Add-Content -Path ./vcpkg/triplets/community/x86-windows-static.cmake "`n`nset(VCPKG_BUILD_TYPE release)"
        Add-Content -Path ./vcpkg/triplets/x64-windows-static.cmake "`n`nset(VCPKG_BUILD_TYPE release)"
        Add-Content -Path ./vcpkg/triplets/x86-windows.cmake "`n`nset(VCPKG_BUILD_TYPE release)"
        Add-Content -Path ./vcpkg/triplets/x64-windows.cmake "`n`nset(VCPKG_BUILD_TYPE release)"
        Set-Content -Path ./vcpkg/scripts/toolchains/windows.cmake ((Get-Content -path ./vcpkg/scripts/toolchains/windows.cmake -Raw) -replace '/Z7','')
      shell: pwsh
    - name: Compile LLVM x86
      run: ./vcpkg/vcpkg.exe install mesa[llvm]:x86-windows
      shell: pwsh
      if: matrix.arch == 'x86'
    - name: Compile LLVM x64
      run: ./vcpkg/vcpkg.exe install mesa[llvm]:x64-windows
      shell: pwsh
      if: matrix.arch == 'x64'
    - name: Upload x86 build
      uses: actions/upload-artifact@v2
      with:
        name: mesa_x86-windows
        path: ./vcpkg/installed/x86-windows/**/*
      if: matrix.arch == 'x86'
    - name: Upload x64 build
      uses: actions/upload-artifact@v2
      with:
        name: mesa_x64-windows
        path: ./vcpkg/installed/x64-windows/**/*
      if: matrix.arch == 'x64'